logging:
  level: INFO
  loggers:
    com.hellobot.ai: DEBUG

slackBotConfig:
  botToken: "xoxb-2394169911889-4972513998802-QzVBVxxXAS1Ay0dgRgcx8s3U"
  signingSecret: "8bca1ab5e9f7f9811a3d7fa141ed1fb0"


