logging:
  level: INFO
  loggers:
    com.hellobot.ai: DEBUG

slackBotConfig:
  # Don't expose, keep them private
  botToken: ${SLACK_BOT_TOKEN} #"<YOUR BOT TOKEN>"
  signingSecret: ${SLACK_SIGNING_SECRET} #"<YOUR SIGN SECRET>"